### ISSUE TITLE
Bot craft table deposit issue

### ISSUE THREAD

**Issue by boly38** [chickarmy/chickenbot-web#87]
🗣️ #77
- The bot builds a crafting table and sometimes does not know how to place it

ℹ️ better inform in the chat of the problem (known PrismarineJS/mineflayer#2757 )
ℹ️ and/or move a few squares and try again (up to 3 times)

**Comment by boly38** [comment]
logs example
````
15:21:24.273 > botActions> labels:on TriggerChatPattern pattern__5-crafting-table_start 5-crafting-table (craftingTable) user:boly38 userChat:table  2 actions
15:21:37.438 > Error: Event blockUpdate:(125, 63, 208) did not fire within timeout of 5000ms
    at onceWithCleanup (C:\WORK\perso\chicken-bot\node_modules\mineflayer\lib\promise_utils.js:62:26)
    at placeBlockWithOptions (C:\WORK\perso\chicken-bot\node_modules\mineflayer\lib\plugins\place_block.js:13:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EventEmitter.placeBlock (C:\WORK\perso\chicken-bot\node_modules\mineflayer\lib\plugins\place_block.js:33:5)
    at async placeCurrentBlockAtClearPlace (file:///C:/WORK/perso/chicken-bot/src/minecraft/util/BlockUtil.js:131:5)
    at async BotAction.craftingTableOrder (file:///C:/WORK/perso/chicken-bot/src/minecraft/botActions.js:113:35)
````

**Comment by boly38** [comment]
- Reproduced: placeBlock error case was to try to placeBlock at player location ! then with retry it was ok

**Comment by boly38** [comment]
The addition for now will be the following
- retry 3 times max (increasing range by 1 each time)
- add tchat to report the target block name + block below name to inform why bot just failed to placeBlock (this to improve undestanding of mineflayer issue)

this is not a full fix but a step ahead
